### ISSUE TITLE
[file request] dxf format of the case files

### ISSUE THREAD

**Issue by fxyu** [rschenk/re-gret#1]
Nice build! I am sourcing the component of this keyboard, and I am ordering the acrylic case from some random local factory. Can you also provide the .dxf format on the case files? 

I afraid if I convert the pdf to dxf file from some online converter, there might be some mis-alignment happens. I can directly drop the files to their to the factory if you provided! Thanks a lot!

**Comment by rschenk** [comment]
Thanks for your interest, I'll see if it's possible with the software I have

**Comment by SeebM** [comment]
Even svg would be nice. Then we could use Inkscape to convert to whatever format needed. I am super excited to building one myself. :D

**Comment by rschenk** [comment]
@fxyu @SeebM I added both DXF and SVG case files, hope they work for ya!
